### ISSUE TITLE
Not an issue.

### ISSUE THREAD

**Issue by regularguy01** [centminmod/centminmod-abuseipdb-reporter#1]
Hello my friend I hope you are well.   You should share you script or a modified version directly to AbuseIPDB.  I am sure they would love not to Leak server data.

As always you have to much time for coding.

Take sometime to be just a Regular Guy..

**Comment by centminmod** [comment]
Cheers @bdacus01. Yes, I've already contacted AbuseIPDB via their contact form as well. Just waiting on a reply.
