### ISSUE TITLE
MAC address is exposed in submitted logs to AbuseIPDB

### ISSUE THREAD

**Issue by Wanabo** [centminmod/centminmod-abuseipdb-reporter#2]
I switched over from the well known Perl script to this Python script.
I love it! Especially the masking of sensitive data before submitting to AbuseIPDB.

But I consider my server's MAC address also as sensitive data. Could you implement masking the server's MAC address, perhaps the Ethernet device as well.

This is the submitted data to AbuseIPDB.
```
Logs: 
May 28 19:57:47 kernel: Firewall: *TCP_IN Blocked* IN=ens2 OUT= MAC=MASKTHISPLEASE SRC=13.40.94.107 DST=0.0.0.x LEN=44 TOS=0x00 PREC=0x00 TTL=35 ID=54192 PROTO=TCP SPT=21345 DPT=32414 WINDOW=1024 RES=0x00 SYN URGP=0
May 28 19:57:49 kernel: Firewall: *TCP_IN Blocked* IN=ens2 OUT= MAC=MASKTHISPLEASE SRC=13.40.94.107 DST=0.0.0.x LEN=44 TOS=0x00 PREC=0x00 TTL=35 ID=57595 PROTO=TCP SPT=21345 DPT=7754 WINDOW=1024 RES=0x00 SYN URGP=0

```

**Comment by centminmod** [comment]
@Wanabo ah MAC addresses! Let me see what I can do about it and Ehternet device name

**Comment by centminmod** [comment]
Might need your help in testing the changes to mask MAC address and ethernet device name as I don't get frequent enough Port Scans to test other than a manual test https://github.com/centminmod/centminmod-abuseipdb-reporter#manual-tests which the below code works for

so in `abuseipdb-reporter.py` find this code

```python
if LOG_MODE == 'full':
    # Truncate masked_logs to no more than 500 characters
    masked_logs = masked_logs[:500]
elif LOG_MODE == 'compact':
    # Truncate masked_logs to no more than 150 characters
    masked_logs = masked_logs[:150]
else:
    # Truncate masked_logs to no more than 150 characters
    masked_logs = masked_logs[:150]
```

and add these lines above it 

```python
# This pattern will match the `MAC=...` pattern in your logs
pattern = r'(MAC=)([0-9A-Fa-f]{2}[:-])+'
# Replace MAC addresses with a 'masked' string
masked_logs = re.sub(pattern, r'\1xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx', masked_logs)

# This pattern will match the `IN=... OUT=...` pattern in your logs
pattern = r'(IN=)(\w+)( OUT=)'
# Replace ethernet device names with a 'masked' string
masked_logs = re.sub(pattern, r'\1ethX\3', masked_logs)
```

so it looks like:

```python
# This pattern will match the `MAC=...` pattern in your logs
pattern = r'(MAC=)([0-9A-Fa-f]{2}[:-])+'
# Replace MAC addresses with a 'masked' string
masked_logs = re.sub(pattern, r'\1xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx', masked_logs)

# This pattern will match the `IN=... OUT=...` pattern in your logs
pattern = r'(IN=)(\w+)( OUT=)'
# Replace ethernet device names with a 'masked' string
masked_logs = re.sub(pattern, r'\1ethX\3', masked_logs)

if LOG_MODE == 'full':
    # Truncate masked_logs to no more than 500 characters
    masked_logs = masked_logs[:500]
elif LOG_MODE == 'compact':
    # Truncate masked_logs to no more than 150 characters
    masked_logs = masked_logs[:150]
else:
    # Truncate masked_logs to no more than 150 characters
    masked_logs = masked_logs[:150]
```

**Comment by BlackTiger63** [comment]
@Wanabo as you should nog, NIC masking is pure nonsense, because it's no private data and totally nothing can be resolved to your nic. For example, eth2 or enps0 are NIC's.
Hundreds of servers around the world use these kind of NIC's so there is absolutely no reason to mask this.

As for the MAC, well.... maybe some things can be looked up by that some way, so you might have a point there.

**Comment by centminmod** [comment]
Thanks @BlackTiger63 for chiming in. Either way I've updated the script for masking both anyway https://github.com/centminmod/centminmod-abuseipdb-reporter/commit/0a3a65d65d0ddfc3ecab40eb6914246d4504c396 :)

**Comment by Wanabo** [comment]
Thanks for all insights. I have implemented the extra lines and will watch for reports at abuseipd to see if it works. I'll report back if I get any results. Thanks for this.

**Comment by Wanabo** [comment]
It's working correctly! 👍

`*Port Scan* detected from 36.134.36.205 (CN/China/-). 11 hits in the last 130 seconds; Ports: *; Direction: in; Trigger: PS_LIMIT; Logs: Jun 12 23:01:46 kernel: Firewall: *TCP_IN Blocked* IN=ethX OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx00 SRC=36.134.36.205 DST=0.0.0.x LEN=52 TOS=0x00 PREC=0x00 TTL=99 ID=7988 DF PROTO=TCP SPT=50581 DPT=21 WINDOW=65535 RES=0x00 CWR ECE SYN URGP=0
Jun 12 23:01:47 kernel: Firewall: *TCP_IN Blocked* IN=ethX OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx00 SRC=36.134.36.205 DST=0.0.0.x LEN=52 TOS=0x00 PREC=0x00 TTL=99 ID=7989 DF PROTO=TCP SPT=50581 DPT=21 WINDOW=65535 RES=0x00 CWR `

**Comment by BlackTiger63** [comment]
I didn't expect otherwise. :)
Good job Eva2000.

**Comment by centminmod** [comment]
Glad to hear :)
