### ISSUE TITLE
IPv6?

### ISSUE THREAD

**Issue by Wanabo** [centminmod/centminmod-abuseipdb-reporter#4]
Not getting much traffic from IPv6 addresses, but it seems that the script can't handle IPv6 addresses for reporting to abuseipdb. (At least when I look with my limited knowledge to the script) The abuseipdb api is IPv6 capable.
On one of my servers ports got scanned from 2001:da8:ff:212::3:1 and CSF did permanently block the address after 5 temp blocks. Unfortunately the ipv6 ip was not reported. CSF/LFD message at the end of this post.
Some others did: https://www.abuseipdb.com/check/2001:da8:ff:212::3:1

I hope you can/will add IPv6 functionality.

Love your abuseipdb-reporter script!

`Time:            Fri Jul 28 14:48:14 2023 +0200
IP:              2001:da8:ff:212::3:1 (Unknown)
Temporary Blocks: 5

Temporary blocks that triggered the permanent block:
Fri Jul 28 08:24:52 2023 *Port Scan* detected from 2001:da8:ff:212::3:1 (Unknown). 11 hits in the last 86 seconds
Fri Jul 28 08:57:47 2023 *Port Scan* detected from 2001:da8:ff:212::3:1 (Unknown). 11 hits in the last 243 seconds
Fri Jul 28 12:13:49 2023 *Port Scan* detected from 2001:da8:ff:212::3:1 (Unknown). 11 hits in the last 216 seconds
Fri Jul 28 12:38:39 2023 *Port Scan* detected from 2001:da8:ff:212::3:1 (Unknown). 11 hits in the last 198 seconds
Fri Jul 28 14:48:13 2023 *Port Scan* detected from 2001:da8:ff:212::3:1 (Unknown). 11 hits in the last 222 seconds
`

**Comment by centminmod** [comment]
Do you get IPv4 submissions?

Make sure it's not in local IP cache which would skip submission https://github.com/centminmod/centminmod-abuseipdb-reporter#local-ip-cache

Also check the debug logs for clues https://github.com/centminmod/centminmod-abuseipdb-reporter#log-inspection and https://github.com/centminmod/centminmod-abuseipdb-reporter#abuseipdb-api-submissions

Also try manual test run and see https://github.com/centminmod/centminmod-abuseipdb-reporter#manual-tests

I did just update the script to fix a logging issue as well as add IPv6 masking/public IP detection support but it doesn't change the API submission routine - just ensures public IPv6 IPs are masked. But see if that helps https://github.com/centminmod/centminmod-abuseipdb-reporter/commit/2bc06e29228a143b29293d27a7b759d6daffbe89

**Comment by Wanabo** [comment]
- Yes IPv4 works fine.
- It was the first IPv6 alarm in a long time, so it wasn't in the local ip cache.
- /var/log/abuseipdb-reporter-api-json.log has no mention of any IPv6 Ip. The error log is empty.
-  I tried manually: # ./abuseipdb-reporter.py "2001:da8:ff:212::3:1" '*' "0" "inout" "360" "(sshd) Failed SSH login from 2001:da8:ff:212::3:1 (VN/Vietnam/-): 5 in the last 3600 secs" "Apr 2 07:18:50 host sshd[7788]: Invalid user free from 2001:da8:ff:212::3:1 port 49518..." "LF_SSHD"                                                     
Received arguments: ['2001:da8:ff:212::3:1', '*', '0', 'inout', '360', '(sshd) Failed SSH login from 2001:da8:ff:212::3:1 (VN/Vietnam/-): 5 in the last 3600 secs', 'Apr 2 07:18:50 host sshd[7788]: Invalid user free from 2001:da8:ff:212::3:1 port 49518...', 'LF_SSHD']

Received Ports: *
Received In/Out: inout
Received Message: (sshd) Failed SSH login from 2001:da8:ff:212::3:1 (VN/Vietnam/-): 5 in the last 3600 secs
Received Logs: Apr 2 07:18:50 host sshd[7788]: Invalid user free from 2001:da8:ff:212::3:1 port 49518...
Received Trigger: LF_SSHD

Sending Ports: *
Sending In/Out: inout
Sending Message: (sshd) Failed SSH login from 2001:da8:ff:212::3:1 (VN/Vietnam/-): 5 in the last 3600 secs
Sending Logs:
Sending Trigger: LF_SSHD

Loaded cache: {}
Cleaned cache: {}
Current cache: {}
IP in cache: False
{
    "detail": "The ip must be a valid IPv4 or IPv6 address (e.g. 8.8.8.8 or 2001:4860:4860::8888).",
    "source": {
        "parameter": "ip"
    },
    "status": 422
}

This is with version 0.3.9
Will try version 0.4.0. Sadly IPv6 blocks are not very common. 

It could be as simple as the notation of the IPv6 format. 2001:da8:ff:212::3:1 versus 2001:0da8:00ff:0212:0000:0000:0003:0001

Edit: with the updated 0.4.0 script I get the same error when trying manually from the command line. Tried both: 2001:da8:ff:212::3:1 versus 2001:0da8:00ff:0212:0000:0000:0003:0001

**Comment by centminmod** [comment]
Does it work if you trying changing

```python
querystring = {
    'ip': url_encoded_ip,
    'categories': categories,
    'comment': masked_comment
}
```
to
```python
querystring = {
    'ip': args.arguments[0], 
    'categories': categories,
    'comment': masked_comment
}
```

**Comment by Wanabo** [comment]
:) Yes that works! See output below and it was correctly submitted to abuseipdb. (Removed it from the results at abuseipdb)

`# ./abuseipdb-reporter.py "2001:da8:ff:212::3:1" '*' "0" "inout" "360" "(sshd) Failed SSH login from 2001:da8:ff:212::3:1 (VN/Vietnam/-): 5 in the last 3600 secs" "Apr 2 07:18:50 host sshd[7788]: Invalid user free from 2001:da8:ff:212::3:1 port 49518..." "LF_SSHD"

Received arguments: ['2001:da8:ff:212::3:1', '*', '0', 'inout', '360', '(sshd) Failed SSH login from 2001:da8:ff:212::3:1 (VN/Vietnam/-): 5 in the last 3600 secs', 'Apr 2 07:18:50 host sshd[7788]: Invalid user free from 2001:da8:ff:212::3:1 port 49518...', 'LF_SSHD']

Received Ports: *
Received In/Out: inout
Received Message: (sshd) Failed SSH login from 2001:da8:ff:212::3:1 (VN/Vietnam/-): 5 in the last 3600 secs
Received Logs: Apr 2 07:18:50 host sshd[7788]: Invalid user free from 2001:da8:ff:212::3:1 port 49518...
Received Trigger: LF_SSHD

Sending Ports: *
Sending In/Out: inout
Sending Message: (sshd) Failed SSH login from 2001:da8:ff:212::3:1 (VN/Vietnam/-): 5 in the last 3600 secs
Sending Logs: Apr 2 07:18:50 sshd[7788]: Invalid user [USERNAME] from 2001:da8:ff:212::3:1 port 49518...
Sending Trigger: LF_SSHD

Loaded cache: {}
Cleaned cache: {}
Current cache: {}
IP in cache: False
{
    "abuseConfidenceScore": 75,
    "ipAddress": "2001:da8:ff:212::3:1"
}
Updated cache: {'2001:da8:ff:212::3:1': 1690614328.76686}
{
    "abuseConfidenceScore": 75,
    "ipAddress": "2001:da8:ff:212::3:1"
}`

**Comment by centminmod** [comment]
Thanks made some updates in 0.4.1 https://github.com/centminmod/centminmod-abuseipdb-reporter/commit/37339896ce257d1f103025a9c8267c5fac3beb47 :)

**Comment by centminmod** [comment]
0.4.2 was released for another bug fix ;)

**Comment by Wanabo** [comment]
You're quick! But now I'm up to date to version 0.4.2!
There are 2 other things I would bring to your attention.
1. https://github.com/centminmod/centminmod-abuseipdb-reporter#abuseipdb-reporterini
- I had to remove the quotes in the ini file for all of the categories. If this is correct please adjust the readme.md.
2. When blocking reason LF_PERMBLOCK_COUNT occurs, the default category, 14 Port Scan, is submitted. Well actually this is the correct category except when you override it in the .ini file. LF_PERMBLOCK_COUNT is not defined in the py script. I'll leave it up to you if it should.

**Comment by centminmod** [comment]
Cheers so you overriding categories in .ini ? do you have an example of what you set?

For default category, that is controlled via `LF_DEFAULT_CATEGORY` variable which is = `14` by default. But you're referring to specifically `LF_PERMBLOCK_COUNT` trigger class being assigned to `14` right?

**Comment by centminmod** [comment]
Ok 0.4.3 is out https://github.com/centminmod/centminmod-abuseipdb-reporter/commit/308246a16a54d059a8341e0e218f563a477db2b4 ^_^

**Comment by Wanabo** [comment]
My current .ini:
[settings]
DEBUG = False
LOG_API_REQUEST = True
LOG_MODE = compact
JSON_LOG_FORMAT = True
JSON_APILOG_FORMAT = True
IGNORE_CLUSTER_SUBMISSIONS = True
API_KEY = REMOVED
mask_hostname = MASKED_HOSTNAME
mask_ip = 0.0.0.x
USERNAME_REPLACEMENT = [USERNAME]
ACCOUNT_REPLACEMENT = [REDACTED]
CACHE_FILE = ip_cache.json
CACHE_DURATION = 900
LF_DEFAULT_CATEGORY              = 23
LF_SSHD_CATEGORY                   = 22
LF_DISTATTACK_CATEGORY         =  4
LF_SMTPAUTH_CATEGORY          = 18
LF_DISTFTP_CATEGORY               =  5
LF_FTPD_CATEGORY                    =  5
LF_MODSEC_CATEGORY              = 21
PS_LIMIT_CATEGORY                   = 14
LF_DISTSMTP_CATEGORY            = 18
CT_LIMIT_CATEGORY                   =  4
LF_DIRECTADMIN_CATEGORY      = 21
LF_CUSTOMTRIGGER_CATEGORY = 21

Note the missing quotes in the CATEGORY part.
I've set LF_DEFAULT_CATEGORY       = 23
23 = IoT Targeted

This way I can see what is not defined as a category in the .py script but is reported to abuseipdb and I can further investigate. That's how I found trigger LF_PERMBLOCK_COUNT

LF_PERMBLOCK_COUNT trigger is being assigned to LF_DEFAULT_CATEGORY, because for LF_PERMBLOCK_COUNT no trigger/category is assigned. 

Your LF_DEFAULT_CATEGORY = 14 (Port Scan), which coincidentally is the correct category for LF_PERMBLOCK_COUNT. But I was hoping to find more undefined categories and report them back to you.

Ha ha, before finishing my answer, you already added it in v0.4.3

**Comment by Wanabo** [comment]
I have found two other non defined categories, LF_IMAPD and LF_POP3D. Checked with search option in abuseipdb.
And perhaps a third LF_HTACCESS, by studying csf.conf. But I can't find any between my submitted reports with the search function. I'll wait and see if LF_HTACCESS comes along.

Proposed categories:
(LF_HTACCESS = 21)
LF_IMAPD = 15 or 18
LF_POP3D = 15 or 18

**Comment by centminmod** [comment]
Sweet thanks for the feedback and suggestions. 0.4.4 updated https://github.com/centminmod/centminmod-abuseipdb-reporter/commit/b9fae931388e5d2046e288068691848f3fb7fd2f

**Comment by Wanabo** [comment]
Again, love your script and I go all the way for it. (If that is a correct English expression)

I'm a perfectionist and I'm glad I was able to contribute to this fantastic script to take it towards perfection. :)
